services:
  team01-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team01-net:
        ipv4_address: 10.7.1.1

  team01-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team01-net:
        ipv4_address: 10.7.1.2

  team01-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team01-net:
        ipv4_address: 10.7.1.3

networks:
  team01-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.1.0/24
          gateway: 10.7.1.254
