services:
  team01-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team01-net:
        ipv4_address: 10.7.1.1

  team01-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team01-net:
        ipv4_address: 10.7.1.2

  team01-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team01-net:
        ipv4_address: 10.7.1.3

  team02-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team02-net:
        ipv4_address: 10.7.2.1

  team02-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team02-net:
        ipv4_address: 10.7.2.2

  team02-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team02-net:
        ipv4_address: 10.7.2.3

  team03-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team03-net:
        ipv4_address: 10.7.3.1

  team03-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team03-net:
        ipv4_address: 10.7.3.2

  team03-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team03-net:
        ipv4_address: 10.7.3.3

  team04-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team04-net:
        ipv4_address: 10.7.4.1

  team04-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team04-net:
        ipv4_address: 10.7.4.2

  team04-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team04-net:
        ipv4_address: 10.7.4.3

  team05-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team05-net:
        ipv4_address: 10.7.5.1

  team05-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team05-net:
        ipv4_address: 10.7.5.2

  team05-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team05-net:
        ipv4_address: 10.7.5.3

  team06-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team06-net:
        ipv4_address: 10.7.6.1

  team06-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team06-net:
        ipv4_address: 10.7.6.2

  team06-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team06-net:
        ipv4_address: 10.7.6.3

  team07-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team07-net:
        ipv4_address: 10.7.7.1

  team07-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team07-net:
        ipv4_address: 10.7.7.2

  team07-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team07-net:
        ipv4_address: 10.7.7.3

  team08-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team08-net:
        ipv4_address: 10.7.8.1

  team08-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team08-net:
        ipv4_address: 10.7.8.2

  team08-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team08-net:
        ipv4_address: 10.7.8.3

  team09-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team09-net:
        ipv4_address: 10.7.9.1

  team09-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team09-net:
        ipv4_address: 10.7.9.2

  team09-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team09-net:
        ipv4_address: 10.7.9.3

  team10-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team10-net:
        ipv4_address: 10.7.10.1

  team10-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team10-net:
        ipv4_address: 10.7.10.2

  team10-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team10-net:
        ipv4_address: 10.7.10.3

  team11-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team11-net:
        ipv4_address: 10.7.11.1

  team11-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team11-net:
        ipv4_address: 10.7.11.2

  team11-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team11-net:
        ipv4_address: 10.7.11.3

  team12-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team12-net:
        ipv4_address: 10.7.12.1

  team12-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team12-net:
        ipv4_address: 10.7.12.2

  team12-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team12-net:
        ipv4_address: 10.7.12.3

  team13-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team13-net:
        ipv4_address: 10.7.13.1

  team13-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team13-net:
        ipv4_address: 10.7.13.2

  team13-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team13-net:
        ipv4_address: 10.7.13.3

  team14-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team14-net:
        ipv4_address: 10.7.14.1

  team14-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team14-net:
        ipv4_address: 10.7.14.2

  team14-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team14-net:
        ipv4_address: 10.7.14.3

  team15-sol:
    image: ctf-sol
    hostname: sol
    networks:
      team15-net:
        ipv4_address: 10.7.15.1

  team15-tau:
    image: ctf-tau
    hostname: tau-ceti
    networks:
      team15-net:
        ipv4_address: 10.7.15.2

  team15-eri:
    image: ctf-eri
    hostname: eridani
    networks:
      team15-net:
        ipv4_address: 10.7.15.3

networks:
  team01-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.1.0/24
          gateway: 10.7.1.254
  team02-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.2.0/24
          gateway: 10.7.2.254
  team03-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.3.0/24
          gateway: 10.7.3.254
  team04-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.4.0/24
          gateway: 10.7.4.254
  team05-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.5.0/24
          gateway: 10.7.5.254
  team06-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.6.0/24
          gateway: 10.7.6.254
  team07-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.7.0/24
          gateway: 10.7.7.254
  team08-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.8.0/24
          gateway: 10.7.8.254
  team09-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.9.0/24
          gateway: 10.7.9.254
  team10-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.10.0/24
          gateway: 10.7.10.254
  team11-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.11.0/24
          gateway: 10.7.11.254
  team12-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.12.0/24
          gateway: 10.7.12.254
  team13-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.13.0/24
          gateway: 10.7.13.254
  team14-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.14.0/24
          gateway: 10.7.14.254
  team15-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.15.0/24
          gateway: 10.7.15.254
