listen=YES
local_enable=YES
write_enable=NO
local_umask=022
chroot_local_user=YES
allow_writeable_chroot=YES
idle_session_timeout=180
pasv_enable=YES
pasv_min_port=60000
pasv_max_port=60010
seccomp_sandbox=NO
